DROP TABLE IF EXISTS pokemon;
DROP TABLE IF EXISTS typeInfo;
DROP TABLE IF EXISTS moveInfo;
DROP TABLE IF EXISTS pokemonType;
DROP TABLE IF EXISTS pokemonMove;

CREATE TABLE pokemon (
	pokemonID INTEGER PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	weight INTEGER NOT NULL
);

CREATE TABLE typeInfo (
	typeID INTEGER PRIMARY KEY NOT NULL,
	name TEXT NOT NULL
);

CREATE TABLE moveInfo (
	moveID INTEGER PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	accuracy INTEGER NULL
);

CREATE TABLE pokemonType (
	pokemonID INTEGER NOT NULL,
	typeID INTEGER NOT NULL
);

CREATE TABLE pokemonMove (
	pokemonID INTEGER NOT NULL,
	moveID INTEGER NOT NULL
);
